server:
  port: 8761
spring:
  application:
    name: Digger-Registry
  config:
    name: digger_registry
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false